/** Bot-owned taxonomy rows. Created by rose-bot; admin CREATE TABLE IF NOT EXISTS so /questions works. */
export const JEV_QUESTIONS_SCHEMA = `
CREATE TABLE IF NOT EXISTS jev_questions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  question_id TEXT NOT NULL UNIQUE,
  type TEXT NOT NULL,
  instructions TEXT NOT NULL,
  criteria TEXT,
  criteria_source TEXT,
  depends_on TEXT,
  enabled INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
`;

export const QUESTION_ID_RE = /^[a-z][a-z0-9_]{0,63}$/;
export const QUESTION_TYPES = new Set(["choice", "score", "noul"]);

export function prettyJson(raw: string | null | undefined) {
  if (raw == null || raw === "") return "";
  try {
    return JSON.stringify(JSON.parse(raw), null, 2);
  } catch {
    return raw;
  }
}

export function parseInstructionsField(raw: string) {
  const trimmed = raw.trim();
  if (!trimmed) return { ok: false as const, error: "Instructions required." };
  if (
    (trimmed.startsWith("{") && trimmed.endsWith("}")) ||
    (trimmed.startsWith("[") && trimmed.endsWith("]"))
  ) {
    try {
      JSON.parse(trimmed);
      return { ok: true as const, value: trimmed };
    } catch {
      return { ok: false as const, error: "Instructions JSON is invalid." };
    }
  }
  return { ok: true as const, value: trimmed };
}

export function parseCriteriaField(type: string, raw: string, criteriaSource: string) {
  const trimmed = raw.trim();
  if (criteriaSource === "countries_in_region") {
    if (!trimmed) return { ok: true as const, value: null as string | null };
  }
  if (type === "noul" && !trimmed) return { ok: true as const, value: null as string | null };
  if (!trimmed) {
    return { ok: false as const, error: "Criteria JSON required for choice and score." };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch {
    return { ok: false as const, error: "Criteria must be JSON." };
  }
  if (type === "choice") {
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
      return { ok: false as const, error: "Choice criteria must be a JSON object of options." };
    }
    const n = Object.keys(parsed as object).length;
    if (n < 1 || n > 255) return { ok: false as const, error: "Choice needs 1–255 options." };
  } else if (type === "score") {
    if (!Array.isArray(parsed) || parsed.length < 2 || parsed.length > 10) {
      return { ok: false as const, error: "Score criteria must be a JSON array of 2–10 levels." };
    }
  } else if (type === "noul") {
    if (parsed && (typeof parsed !== "object" || Array.isArray(parsed))) {
      return { ok: false as const, error: "Noul criteria must be a JSON object { true, false } or empty." };
    }
  }
  return { ok: true as const, value: JSON.stringify(parsed) };
}

export function readQuestionForm(formData: FormData) {
  const questionId = String(formData.get("question_id") || "").trim();
  const type = String(formData.get("type") || "").trim().toLowerCase();
  const notes = String(formData.get("notes") || "").trim() || null;
  const dependsOn = String(formData.get("depends_on") || "").trim() || null;
  const criteriaSource = String(formData.get("criteria_source") || "").trim() || null;
  const sortOrder = Number(formData.get("sort_order") || 0);
  const enabled = formData.get("enabled") ? 1 : 0;
  if (!QUESTION_ID_RE.test(questionId)) {
    return { ok: false as const, error: "question_id must match [a-z][a-z0-9_]{0,63}." };
  }
  if (!QUESTION_TYPES.has(type)) {
    return { ok: false as const, error: "type must be choice, score, or noul." };
  }
  if (criteriaSource && criteriaSource !== "countries_in_region") {
    return { ok: false as const, error: "criteria_source must be empty or countries_in_region." };
  }
  const instructions = parseInstructionsField(String(formData.get("instructions") || ""));
  if (!instructions.ok) return instructions;
  const criteria = parseCriteriaField(type, String(formData.get("criteria") || ""), criteriaSource || "");
  if (!criteria.ok) return criteria;
  return {
    ok: true as const,
    value: {
      questionId,
      type,
      instructions: instructions.value,
      criteria: criteria.value,
      criteriaSource,
      dependsOn,
      enabled,
      sortOrder: Number.isFinite(sortOrder) ? sortOrder : 0,
      notes,
    },
  };
}
